### ISSUE TITLE
MSLearn Exercise - Create a MongoDB DB app using the Azure Cosmos DB for MongoDB requires SDK version update

### ISSUE THREAD

**Issue by sergeevgk** [MicrosoftLearning/mslearn-cosmosdb#7]
I was doing this exercise:
https://learn.microsoft.com/en-us/training/modules/get-started-mongodb-api-azure-cosmos-db/6-exercise-create-cosmos-db-mongodb-application?pivots=csharp

When trying to use the sandbox environment with Azure CLI and complete the exercise there, the following message is displayed on running `dotnet run`:

``` You must install or update .NET to run this application.

App: /home/<username>/mslearn-cosmosdb/api-for-mongodb/01-create-mongodb-objects/csharp/bin/Debug/net6.0/app
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/share/dotnet

The following frameworks were found:
  7.0.16 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  8.0.2 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=linux-x64&os=mariner.2.0
```

![image](https://github.com/MicrosoftLearning/mslearn-cosmosdb/assets/25644531/fcadc46b-2081-40f0-8035-e332233a459a)

Strangely, changing TargetFramework to `net8.0` leads to the following error despite having the .NET 8.0.2 installed in the sandbox (as stated in the previous message):
```
/usr/share/dotnet/sdk/7.0.406/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(160,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 8.0.  Either target .NET 7.0 or lower, or use a version of the .NET SDK that supports .NET 8.0. Download the .NET SDK from https://aka.ms/dotnet/download [/home/gosha199904/mslearn-cosmosdb/api-for-mongodb/01-create-mongodb-objects/csharp/app.csproj]

The build failed. Fix the build errors and run again.
```

![image](https://github.com/MicrosoftLearning/mslearn-cosmosdb/assets/25644531/533bc1c0-9059-48ab-8cf4-4d343dcdb3f3)

And `dotnet --list-sdks` gives the following: 
"7.0.406 [/usr/share/dotnet/sdk]"

After changing the default SDK Target framework to `net7.0` the problem is solved.
 `<TargetFramework>net7.0</TargetFramework>` in mslearn-cosmosdb/api-for-mongodb/01-create-mongodb-objects/csharp/app.csproj

However, this is not an LTS version of .NET, so it would be great to either:
- Update the default version of .NET SDK shared for Sandbox users to .NET 8, or
- Install the .NET 6 version of SDK in the sandbox

I have only the opportunity to change the SDK version to `.net7.0` in pull request, so I am not sure if it is an appropriate change.

**Comment by sergeevgk** [comment]
Created a pull request for this issue: https://github.com/MicrosoftLearning/mslearn-cosmosdb/pull/9
Waiting for anyone to check my comments on this issue

**Comment by afelix-95** [comment]
Sorry for the delay on checking this issue! Indeed, .NET 7 is an out of support version now, but updating the .NET SDK used in the sandbox is out of our scope. As soon as the platform team updates it to support .NET 8, we will update the lab files accordingly. In the meantime, I'll reopen your PR and merge it since that is the actual fix to this issue for now.
